# SPDX-License-Identifier: GPL-3.0-or-later
"""README.md for a packaged kit, generated from the contract and the
measured validation and export results."""

IMPORT_NOTES = {
    "unity": [
        "Drop the FBX files into your Assets folder. Each file holds the piece as",
        "`<name>_LOD0`, `_LOD1`, `_LOD2` (Unity builds a LOD Group from these suffixes)",
        "plus `UCX_<name>_NN` convex collider meshes. Unity does not turn UCX_ meshes",
        "into colliders by itself: use an asset postprocessor, or add Mesh Colliders",
        "(Convex) to them and disable their renderers.",
    ],
    "unreal": [
        "Import `<name>.fbx` as a Static Mesh; the embedded `UCX_<name>_NN` meshes become",
        "its convex collision. Import `<name>_LOD1.fbx` and `_LOD2.fbx` as LODs of that",
        "mesh (Static Mesh Editor, LOD Import). Files are in meters with declared units;",
        "the importer converts to centimeters.",
    ],
    "godot": [
        "Copy the GLB files into your project. Collider meshes carry the",
        "`-convcolonly` import hint, so Godot creates convex StaticBody3D shapes.",
        "Godot generates mesh LODs on import; `<name>_LOD1.glb` and `_LOD2.glb` are",
        "provided for projects that want hand-made LODs.",
    ],
    "gltf_web": [
        "Standard glTF 2.0 binary files for three.js, Babylon.js or model-viewer.",
        "No Draco compression. `<name>_LOD1.glb` and `_LOD2.glb` are lower detail",
        "versions; `<name>_colliders.glb` holds simple convex collision shapes.",
    ],
    "stl_print": [
        "Print the STL files flat as exported, base down. See `print_settings.md`",
        "for printer settings, measured wall thickness and the clip system.",
    ],
}


def kit_readme(contract, info, manifest, summary, demo):
    kit = contract["kit"]
    profile = contract["profile"]
    legal = contract["legal"]
    cell = profile["cell_size"]
    units = profile["units"]
    checks = summary.get("checks", {})
    passed = sum(v["pass"] for v in checks.values())
    failed = sum(v["fail"] for v in checks.values())
    lines = [
        f"# {kit['name']} ({profile['name']})",
        "",
        kit.get("description", ""),
        "",
        "## License",
        "",
    ]
    if legal["license"] == "CC0-1.0":
        lines += ["These assets are dedicated to the public domain under CC0 1.0 Universal",
                  "(see LICENSE). Credit is appreciated but not required."]
    else:
        lines += ["These assets are licensed under the commercial EULA in LICENSE."]
    lines += [
        "",
        "## Grid",
        "",
        f"One grid cell is {cell} {units}. Every piece has its pivot at the minimum corner",
        "of its footprint on the floor, and snaps edge to edge on that grid with 90 degree",
        "rotations.",
        "",
        "## Pieces",
        "",
        "| Piece | Footprint (cells) | Height (cells) | Variants |",
        "|---|---|---|---|",
    ]
    for p in contract["pieces"]:
        fx, fy = p["footprint_cells"]
        lines.append(f"| {p['id']} | {fx:g} x {fy:g} | {p['height_cells']:g} | "
                     f"{', '.join(contract['style']['variants'])} |")
    lines += ["", "## Importing", ""] + IMPORT_NOTES.get(profile["name"], []) + [
        "",
        "## How this pack was made",
        "",
        f"Generated by `{info.id}` {info.version} with seed {manifest['seed']} in Blender "
        f"{manifest['blender']}. Generators are deterministic code: rebuilding with the same",
        "seed gives byte-identical files. No AI-generated content, no external textures,",
        "HDRIs or fonts.",
        "",
        f"Validation: {passed} checks passed, {failed} failed, across {len(summary.get('pieces', {}))} "
        "piece variants (see validation_summary.json).",
        f"Export: {len(manifest['files'])} files, each re-imported and matched "
        f"({'all passed' if manifest['roundtrip_passed'] else 'FAILURES, see manifest.json'}).",
    ]
    if demo:
        lines.append(f"Grid snap: demo room of {demo['pieces_placed']} pieces, {demo['seam_pairs']} seams, "
                     f"max seam deviation {demo['max_seam_deviation']:.2g} {units}.")
    lines.append("")
    return "\n".join(lines)
