# SPDX-License-Identifier: GPL-3.0-or-later
# Keeps the SHA-pinned GitHub Actions in .github/workflows current. The
# pinned Blender versions in ci.yml are bumped by hand.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
